name: Test Environment CI/CD

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test-and-lint:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Linting
        run: |
          pip install flake8
          flake8 backend/
      - name: Run Tests
        run: |
          pip install pytest
          pytest backend/tests/

  deploy:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    needs: test-and-lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Backend
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ vars.RENDER_SERVICE_ID }}
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/v1/services/${{ vars.RENDER_SERVICE_ID }}/deploys

      - name: Deploy Frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          curl -X POST -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{}' \
          https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/builds
